name: Nova
options:
  bundleIdPrefix: com.simpleintelligence
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  Nova:
    type: application
    platform: iOS
    sources:
      - Nova
    settings:
      base:
        INFOPLIST_FILE: Nova/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.simpleintelligence.nova
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: SocketIO
      - package: GoogleSignIn
      - package: WebRTC

packages:
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    from: "16.1.1"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: "125.0.0"
